stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - powershell ./mvnw clean install
    - echo "Compile complete."

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - powershell ./mvnw test
    - echo "Unit tests completed."

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - powershell ./mvnw checkstyle:check
    - echo "Linting completed."

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - powershell start /b java -jar target/*.jar
    - echo "Application successfully deployed."
