stages:
  - Stop tomcat
  - Build
  - Copy
  - Start tomcat

Stop:
  stage: Stop tomcat
  only:
    - dev
  script:
    - sudo /usr/local/lib/apache-tomcat-8.5.57/bin/shutdown.sh -force

Build:
  stage: Build
  only:
    - dev
  cache:
    paths:
      - build/*
  script:
    - gradle bootWar

Copy:
  stage: Copy
  only:
    - dev
  cache:
    paths:
      - build/*
  script:
    - sudo rm -rf /usr/local/lib/apache-tomcat-8.5.57/webapps/sample.war
    - sudo cp ./build/libs/sample.war /usr/local/lib/apache-tomcat-8.5.57/webapps/sample.war

Start:
  stage: Start tomcat
  only:
    - dev
  cache:
    paths:
      - build/*
  script:
    - sudo /usr/local/lib/apache-tomcat-8.5.57/bin/startup.sh
