services:
  spring:
    container_name: spring
    image: spring-app
    networks:
      - app-network
  nginx-react:
    container_name: nginx-react
    image: nginx:alpine
    volumes:
      - /home/ubuntu/templates-react:/etc/nginx/templates
      - /home/ubuntu/nginx-react/logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    external: true