services:
  spring:
    container_name: spring
    image: spring-app
    networks:
      -  app-network
  nginx-react:
    container_name: nginx-react
    image: nginx:alpine
    volumes:
      - ./Front-End/build:/usr/share/nginx/html
      - /home/ubuntu/nginx-react/nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/nginx-react/logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    external: true