services:
  spring1:
    container_name: spring1
    image: spring-app
    networks:
      - app-network

  spring2:
    container_name: spring2
    image: spring-app
    networks:
      - app-network

  spring3:
    container_name: spring3
    image: spring-app
    networks:
      - app-network

  nginx-react1:
    container_name: nginx-react1
    image: nginx:alpine
    volumes:
      - /home/ubuntu/templates-react:/etc/nginx/templates
      - /home/ubuntu/nginx-react/logs:/var/log/nginx
    networks:
      - app-network

  nginx-react2:
    container_name: nginx-react2
    image: nginx:alpine
    volumes:
      - /home/ubuntu/templates-react:/etc/nginx/templates
      - /home/ubuntu/nginx-react/logs:/var/log/nginx
    networks:
      - app-network

  nginx-react3:
    container_name: nginx-react3
    image: nginx:alpine
    volumes:
      - /home/ubuntu/templates-react:/etc/nginx/templates
      - /home/ubuntu/nginx-react/logs:/var/log/nginx
    networks:
      - app-network

networks:
  app-network:
    external: true
