server:
  servlet:
    context-path: /api
spring:
  profiles:
    include: key
  datasource:
    url: jdbc:mysql://i11b102.p.ssafy.io:${dbport}/safefoodtruck
    username: root
    password: ${mysqlpassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${google-email}
    password: ${google-app-password}
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000 #1초
      mail.starttls.enable: true
      mail.smtp.auth: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        diarect: org.hibernate.dialect.MysqlDialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: false  # sql 쿼리를 보여줍니다.
        format_sql: false  # sql query formatting
        use_sql_comments: false  # sql 쿼리의 추가정보를 보여줍니다.

springdoc:
  swagger-ui:
    path: ${swagger-url}

logging:
  level:
    org.hibernate.SQL: info

jwt:
  expiration_time: 3600000 #1시간
  secret: ${JWT}

kakao:
  grant-type: authorization_code
  client-id: ${kakao-client-id}
  redirect-uri: ${kakao-redirect-uri}

openvidu:
  url: ${OpenviduURL}
  secret: ${OpenviduSecret}
